name: Deploy to VPS on push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t myapp:latest ./backend

      - name: Save Docker image as tar
        run: docker save myapp:latest -o myapp.tar

      - name: Fix permissions for scp
        run: chmod 644 myapp.tar

      - name: Copy Docker image to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: deploy
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "myapp.tar"
          target: "~/deploy/"

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: deploy
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            mkdir -p ~/deploy
            cd ~/deploy

            # Carrega a imagem e reinicia o container
            docker load -i myapp.tar
            docker stop myapp || true
            docker rm myapp || true

            if [ -f ".env" ]; then
              echo "✅ Usando variáveis de ambiente do .env"
              docker run -d --name myapp --env-file .env -p 8000:8000 myapp:latest
            else
              echo "⚠️  .env não encontrado, rodando sem variáveis"
              docker run -d --name myapp -p 8000:8000 myapp:latest
            fi
